
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BLOQUE BLOQUECLASE CHAR CLASS CORCHETEDER CORCHETEIZQ CTEI FLOAT FUNCION ID INT LLAVEDER LLAVEIZQ MAIN PARENTESISDER PARENTESISIZQ PROGRAM PUNTOCOMA VARprograma : PROGRAM ID PUNTOCOMA main\n                | PROGRAM ID PUNTOCOMA clase main\n                | PROGRAM ID PUNTOCOMA clase var main\n                | PROGRAM ID PUNTOCOMA clase var FUNCION mainmain : MAIN PARENTESISIZQ PARENTESISDER LLAVEIZQ LLAVEDER\n            | MAIN PARENTESISIZQ PARENTESISDER LLAVEIZQ BLOQUE LLAVEDERclase : CLASS ID LLAVEIZQ LLAVEDER PUNTOCOMA\n            | CLASS ID LLAVEIZQ BLOQUECLASE LLAVEDER PUNTOCOMAvar : VAR varpvarp : tipo_compuesto ID PUNTOCOMA\n            | tipo_compuesto ID PUNTOCOMA varp\n            | tipo_simple ID PUNTOCOMA\n            | tipo_simple ID PUNTOCOMA varp\n            | tipo_simple ID CORCHETEIZQ CTEI CORCHETEDER PUNTOCOMA\n            | tipo_simple ID CORCHETEIZQ CTEI CORCHETEDER PUNTOCOMA varp\n            | tipo_simple ID CORCHETEIZQ CTEI CORCHETEDER CORCHETEIZQ CTEI CORCHETEDER PUNTOCOMA\n            | tipo_simple ID CORCHETEIZQ CTEI CORCHETEDER CORCHETEIZQ CTEI CORCHETEDER PUNTOCOMA varptipo_simple : INT\n                    | FLOAT\n                    | CHARtipo_compuesto : ID'
    
_lr_action_items = {'PROGRAM':([0,],[2,]),'$end':([1,5,9,14,25,34,41,],[0,-1,-2,-3,-4,-5,-6,]),'ID':([2,8,11,17,18,19,20,21,22,31,32,45,49,],[3,13,18,26,-21,27,-18,-19,-20,18,18,18,18,]),'PUNTOCOMA':([3,26,27,29,37,43,48,],[4,31,32,36,42,45,49,]),'MAIN':([4,6,10,15,16,31,32,36,38,39,42,45,47,49,50,],[7,7,7,7,-9,-10,-12,-7,-11,-13,-8,-14,-15,-16,-17,]),'CLASS':([4,],[8,]),'VAR':([6,36,42,],[11,-7,-8,]),'PARENTESISIZQ':([7,],[12,]),'FUNCION':([10,16,31,32,38,39,45,47,49,50,],[15,-9,-10,-12,-11,-13,-14,-15,-16,-17,]),'INT':([11,31,32,45,49,],[20,20,20,20,20,]),'FLOAT':([11,31,32,45,49,],[21,21,21,21,21,]),'CHAR':([11,31,32,45,49,],[22,22,22,22,22,]),'PARENTESISDER':([12,],[23,]),'LLAVEIZQ':([13,23,],[24,28,]),'LLAVEDER':([24,28,30,35,],[29,34,37,41,]),'BLOQUECLASE':([24,],[30,]),'CORCHETEIZQ':([27,43,],[33,44,]),'BLOQUE':([28,],[35,]),'CTEI':([33,44,],[40,46,]),'CORCHETEDER':([40,46,],[43,48,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'main':([4,6,10,15,],[5,9,14,25,]),'clase':([4,],[6,]),'var':([6,],[10,]),'varp':([11,31,32,45,49,],[16,38,39,47,50,]),'tipo_compuesto':([11,31,32,45,49,],[17,17,17,17,17,]),'tipo_simple':([11,31,32,45,49,],[19,19,19,19,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> PROGRAM ID PUNTOCOMA main','programa',4,'p_programa','scpa.py',75),
  ('programa -> PROGRAM ID PUNTOCOMA clase main','programa',5,'p_programa','scpa.py',76),
  ('programa -> PROGRAM ID PUNTOCOMA clase var main','programa',6,'p_programa','scpa.py',77),
  ('programa -> PROGRAM ID PUNTOCOMA clase var FUNCION main','programa',7,'p_programa','scpa.py',78),
  ('main -> MAIN PARENTESISIZQ PARENTESISDER LLAVEIZQ LLAVEDER','main',5,'p_main','scpa.py',82),
  ('main -> MAIN PARENTESISIZQ PARENTESISDER LLAVEIZQ BLOQUE LLAVEDER','main',6,'p_main','scpa.py',83),
  ('clase -> CLASS ID LLAVEIZQ LLAVEDER PUNTOCOMA','clase',5,'p_clase','scpa.py',86),
  ('clase -> CLASS ID LLAVEIZQ BLOQUECLASE LLAVEDER PUNTOCOMA','clase',6,'p_clase','scpa.py',87),
  ('var -> VAR varp','var',2,'p_var','scpa.py',90),
  ('varp -> tipo_compuesto ID PUNTOCOMA','varp',3,'p_varp','scpa.py',93),
  ('varp -> tipo_compuesto ID PUNTOCOMA varp','varp',4,'p_varp','scpa.py',94),
  ('varp -> tipo_simple ID PUNTOCOMA','varp',3,'p_varp','scpa.py',95),
  ('varp -> tipo_simple ID PUNTOCOMA varp','varp',4,'p_varp','scpa.py',96),
  ('varp -> tipo_simple ID CORCHETEIZQ CTEI CORCHETEDER PUNTOCOMA','varp',6,'p_varp','scpa.py',97),
  ('varp -> tipo_simple ID CORCHETEIZQ CTEI CORCHETEDER PUNTOCOMA varp','varp',7,'p_varp','scpa.py',98),
  ('varp -> tipo_simple ID CORCHETEIZQ CTEI CORCHETEDER CORCHETEIZQ CTEI CORCHETEDER PUNTOCOMA','varp',9,'p_varp','scpa.py',99),
  ('varp -> tipo_simple ID CORCHETEIZQ CTEI CORCHETEDER CORCHETEIZQ CTEI CORCHETEDER PUNTOCOMA varp','varp',10,'p_varp','scpa.py',100),
  ('tipo_simple -> INT','tipo_simple',1,'p_tipo_simple','scpa.py',103),
  ('tipo_simple -> FLOAT','tipo_simple',1,'p_tipo_simple','scpa.py',104),
  ('tipo_simple -> CHAR','tipo_simple',1,'p_tipo_simple','scpa.py',105),
  ('tipo_compuesto -> ID','tipo_compuesto',1,'p_tipo_compuesto','scpa.py',108),
]
